name: Bank
version: ${project.version}
main: me.pljr.bank.Bank
api-version: 1.13
authors: [9hx]
depend: [PLJRApi]
softdepend: [PlaceholderAPI]
description: Plugin for in-game Banks.
commands:
  bank:
    description: Main command for Banks.
  abank:
    description: Admin command for Banks.
