package me.pljr.bank.enums;

public enum Lang {
    NO_CONSOLE,
    ADD_SUCCESS,
    ADD_FAILURE_TOO_MUCH,
    ADD_FAILURE_NOT_ENOUGH,
    REMOVE_SUCCESS,
    REMOVE_FAILURE_TOO_MUCH,
    SHOW_PLAYER,
    PERM_YES,
    PERM_NO,
    BUY_SUCCESS,
    BUY_FAILURE,
    NO_POSITIVE,
    ADMIN_SET_SUCCESS,
    ADMIN_SET_SUCCESS_NOTIFY,
    ADMIN_ADD_SUCCESS,
    ADMIN_ADD_SUCCESS_NOTIFY,
    ADMIN_REMOVE_SUCCESS,
    ADMIN_REMOVE_FAILURE_TOO_MUCH,
    ADMIN_REMOVE_SUCCESS_NOTIFY
}
